# This Document can be used to copy Files from controller to target machines
-
  name: Copy file to target servers
  hosts: all
  tasks:
    - name: Copy file
      copy:
        src: /tmp/test-file.txt
        dest: /tmp/test-file.txt
